name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

    # Setup Ruby and Bundler
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version, .tool-versions or mise.toml
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
         
      - name: Setup node
        uses: actions/setup-node@v3
        
      - name: Install project gems
        run: bundle install
          
      - name: Install Appium and XCUITest Driver
        run: |
          npm install -g appium
          appium driver install xcuitest
          appium -v
          
      - name: Start Appium Server in Background
        run: appium &>/dev/null &
          
      - name: Test
        run: bundle exec rspec --format html --out spec/test-results.html
          
      - name: Archive test coverage results
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-report
          path: spec/test-results.html
