name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3

      # --- NEW STEP TO WARM UP XCODE ---
      - name: Warm up Xcode and SDK
        run: |
          echo "Running xcrun to determine SDK version..."
          xcrun --sdk iphonesimulator --show-sdk-version
          echo "Xcode SDK check complete."
          
      - name: Install Appium and XCUITest Driver
        run: |
          npm install -g appium
          appium driver install xcuitest
          
      - name: Start Appium Server and Wait
        run: |
          appium &>/dev/null &
          echo "Waiting for Appium server to start..."
          timeout=60
          while ! curl -s http://127.0.0.1:4723/status && [ $timeout -gt 0 ]; do
            sleep 1
            timeout=$((timeout-1))
          done
          if [ $timeout -eq 0 ]; then
            echo "Appium server failed to start."
            exit 1
          fi
          echo "Appium server is ready."

      - name: List Available Simulators
        run: xcrun simctl list devices
          
      - name: Test
        run: bundle exec rspec --format html --out spec/test-results.html
          
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-report
          path: spec/test-results.html
